server:
  port: 8002
spring:
  application:
    name: upload-server
  servlet:
    multipart:
      max-file-size: 5MB   #限制上传文件大小
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka