server:
  port: 10010
spring:
  application:
    name: gateway-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api  #添加路由前缀
  routes:
    item-server: /item/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #熔断超时时长
ribbon:
  ConnectTimeout: 1000  #链接超时时长
  ReadTimeout:  3500  #读取超时时长
  MaxAutoRetries: 0   #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数